# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Ronan Paugam'
tagline:          'My Research'
description:      'Research in Fire/Atmospheric Science'
url:              http://pogam.github.io
baseurl:          /

author:
  name:           'Ronan Paugam'

paginate:         1

# Custom vars
version:          2.1.0
#
#github:
#  repo:           https://github.com/pogam

plugins: [jekyll-paginate,jekyll-gist]
