# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Ronan Paugam'
tagline:          'My Research'
description:      'Research in Fire/Atmospheric Science'
url:              "https://ronanpaugam.github.io"
baseurl:          "/"

author:
  name:           'Ronan Paugam'
  orcid: "https://orcid.org/0000-0001-6429-6910"
  github: "pogam"
  researchgate: "https://www.researchgate.net/profile/Ronan_Paugam"
  googlescholar: "https://scholar.google.com/citations?user=sp6qiIEAAAAJ&hl=en"
  publons: "https://publons.com/researcher/1556045/ronan-paugam/"

paginate:         1

# Custom vars
version:          2.1.0
#
#github:
#  repo:           https://github.com/ronanpaugam

#plugins
gems : [jekyll-paginate,jekyll-gist]
